"""Skill type definitions for the skills system."""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SkillCategory(str, Enum):
    """Skill categories."""

    DIAGNOSTIC = "diagnostic"
    DEDUP = "dedup"
    FEEDBACK = "feedback"
    SCOPE = "scope"


class SkillPriority(int, Enum):
    """Skill execution priority (lower is higher priority)."""

    CRITICAL = 0
    HIGH = 1
    MEDIUM = 2
    LOW = 3


class SkillResult(BaseModel):
    """Result returned by a skill execution."""

    skill_name: str = ""
    category: SkillCategory = SkillCategory.DIAGNOSTIC
    success: bool = True
    data: Dict[str, Any] = Field(default_factory=dict)
    suggestions: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    execution_time_ms: int = 0

    def model_post_init(self, __context: Any) -> None:
        if isinstance(self.category, str):
            self.category = SkillCategory(self.category)


class CommandHistoryItem(BaseModel):
    """A single command in execution history."""

    command: str = ""
    command_type: str = "unknown"
    risk_level: str = "high"
    exit_code: Optional[int] = None
    stdout: str = ""
    stderr: str = ""
    duration_ms: int = 0
    timestamp: Optional[float] = None
    executed: bool = False
    skipped: bool = False
    skip_reason: Optional[str] = None


class TargetScope(BaseModel):
    """Execution target scope information."""

    target_kind: str = "runtime_node"
    target_identity: str = "runtime:local"
    namespace: Optional[str] = None
    labels: List[str] = Field(default_factory=list)
    service_name: Optional[str] = None
    database: Optional[str] = None
    resource: Optional[str] = None
    confidence: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "target_kind": self.target_kind,
            "target_identity": self.target_identity,
            "namespace": self.namespace,
            "labels": self.labels,
            "service_name": self.service_name,
            "database": self.database,
            "resource": self.resource,
            "confidence": self.confidence,
        }


class DiagnosticContext(BaseModel):
    """Context passed to skills for execution."""

    session_id: str = ""
    trace_id: Optional[str] = None
    request_id: Optional[str] = None
    service_name: Optional[str] = None
    analysis_type: str = "log"
    command_history: List[Dict[str, Any]] = Field(default_factory=list)
    target_scope: Dict[str, Any] = Field(default_factory=dict)
    analysis_mode: str = "diagnostic"

    def model_post_init(self, __context: Any) -> None:
        if isinstance(self.target_scope, TargetScope):
            self.target_scope = self.target_scope.to_dict()

    def add_command(self, command: str, **kwargs: Any) -> None:
        item = CommandHistoryItem(command=command, **kwargs)
        self.command_history.append(item.model_dump(exclude_none=True))


class SkillSuggestion(BaseModel):
    """A suggestion generated by a skill."""

    skill_name: str
    command: str
    reason: str = ""
    priority: SkillPriority = SkillPriority.MEDIUM
    skip_duplicates: bool = True
    use_cache: bool = True


class DeduplicationResult(BaseModel):
    """Result of command deduplication."""

    new_commands: List[str] = Field(default_factory=list)
    duplicate_commands: List[Dict[str, Any]] = Field(default_factory=list)
    equivalent_commands: List[Dict[str, Any]] = Field(default_factory=list)
    deduplication_ratio: float = 0.0
    cache_hits: List[Dict[str, Any]] = Field(default_factory=list)
    cache_misses: List[str] = Field(default_factory=list)
    cache_hit_rate: float = 0.0


class FormattedOutput(BaseModel):
    """Formatted command output."""

    command: str
    status: str = "unknown"
    summary: str = ""
    key_findings: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    truncated: bool = False
    exit_code: Optional[int] = None


class InterpretationResult(BaseModel):
    """Interpretation of command execution result."""

    command: str
    command_type: str = "unknown"
    findings: List[str] = Field(default_factory=list)
    summary: str = ""
    has_errors: bool = False
    error_message: Optional[str] = None
    row_count: Optional[int] = None


class ResolvedTarget(BaseModel):
    """Resolved execution target."""

    command: str
    target_kind: str = "runtime_node"
    target_identity: str = "runtime:local"
    executor_type: str = "local_process"
    executor_profile: str = "local-default"
    requires_write_permission: bool = False
    approved: bool = False
