apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-hosts-config
  namespace: islap
data:
  config.yaml: |
    node-3:
      host: 10.0.0.1
      user: root
      port: 22
      key_file: /etc/ssh-keys/node-3/id_rsa
    node-4:
      host: 10.0.0.2
      user: root
      port: 22
      key_file: /etc/ssh-keys/node-4/id_rsa
