#!/usr/bin/env python3
"""
同步各服务 runtime requirements（单一来源生成）。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

PACKAGE_VERSIONS = {
    "aiokafka": "0.12.0",
    "aiohttp": "3.9.5",
    "clickhouse-driver": "0.2.10",
    "fastapi": "0.104.1",
    "httpx": "0.25.2",
    "langchain-core": "0.3.10",
    "langgraph": "0.2.20",
    "neo4j": "5.14.0",
    "openai": "1.63.0",
    "opentelemetry-api": "1.22.0",
    "opentelemetry-exporter-otlp": "1.22.0",
    "opentelemetry-instrumentation-fastapi": "0.43b0",
    "opentelemetry-instrumentation-requests": "0.43b0",
    "opentelemetry-proto": "1.22.0",
    "prometheus-client": "0.19.0",
    "protobuf": "4.25.1",
    "pydantic": "2.5.2",
    "python-dateutil": "2.8.2",
    "python-json-logger": "2.0.7",
    "requests": "2.31.0",
    "tenacity": "8.2.3",
    "temporalio": "1.9.0",
    "uvicorn[standard]": "0.24.0",
}

SERVICE_REQUIREMENTS = {
    "ai-service/requirements-runtime.txt": [
        "fastapi",
        "uvicorn[standard]",
        "pydantic",
        "clickhouse-driver",
        "neo4j",
        "requests",
        "openai",
        "langchain-core",
        "langgraph",
        "temporalio",
        "prometheus-client",
        "tenacity",
        "python-json-logger",
        "opentelemetry-api",
        "opentelemetry-exporter-otlp",
        "opentelemetry-instrumentation-fastapi",
        "opentelemetry-instrumentation-requests",
        "opentelemetry-proto",
        "protobuf",
    ],
    "query-service/requirements-runtime.txt": [
        "fastapi",
        "uvicorn[standard]",
        "pydantic",
        "clickhouse-driver",
        "neo4j",
        "requests",
        "tenacity",
        "python-json-logger",
        "opentelemetry-api",
        "opentelemetry-exporter-otlp",
        "opentelemetry-instrumentation-fastapi",
        "opentelemetry-instrumentation-requests",
        "opentelemetry-proto",
        "protobuf",
    ],
    "semantic-engine/requirements-runtime.txt": [
        "fastapi",
        "uvicorn[standard]",
        "pydantic",
        "clickhouse-driver",
        "neo4j",
        "requests",
        "tenacity",
        "python-json-logger",
        "opentelemetry-api",
        "opentelemetry-exporter-otlp",
        "opentelemetry-instrumentation-fastapi",
        "opentelemetry-instrumentation-requests",
        "opentelemetry-proto",
        "protobuf",
        "aiokafka",
        "aiohttp",
    ],
    "topology-service/requirements-runtime.txt": [
        "fastapi",
        "uvicorn[standard]",
        "pydantic",
        "clickhouse-driver",
        "neo4j",
        "requests",
        "tenacity",
        "python-json-logger",
        "opentelemetry-api",
        "opentelemetry-exporter-otlp",
        "opentelemetry-instrumentation-fastapi",
        "opentelemetry-instrumentation-requests",
        "opentelemetry-proto",
        "protobuf",
    ],
}


def _render_requirements(keys: list[str]) -> str:
    lines = [
        "# AUTO-GENERATED by scripts/sync-runtime-requirements.py.",
        "# Do not edit manually; update PACKAGE_VERSIONS/SERVICE_REQUIREMENTS in the script.",
        "",
    ]
    for key in keys:
        version = PACKAGE_VERSIONS[key]
        lines.append(f"{key}=={version}")
    lines.append("")
    return "\n".join(lines)


def sync_runtime_requirements(check_only: bool) -> int:
    mismatched_files: list[str] = []

    for relative_path, package_keys in SERVICE_REQUIREMENTS.items():
        target_path = REPO_ROOT / relative_path
        rendered = _render_requirements(package_keys)
        current = target_path.read_text(encoding="utf-8") if target_path.exists() else ""
        if current != rendered:
            mismatched_files.append(relative_path)
            if not check_only:
                target_path.write_text(rendered, encoding="utf-8")

    if not mismatched_files:
        print("runtime requirements are up to date")
        return 0

    if check_only:
        print("runtime requirements out of date:")
        for path in mismatched_files:
            print(f"- {path}")
        return 1

    print("updated runtime requirements:")
    for path in mismatched_files:
        print(f"- {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync runtime requirements for all services.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only check for drift and exit non-zero when files are outdated.",
    )
    args = parser.parse_args()
    return sync_runtime_requirements(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
